import {Constants, Colors} from '../../utils';
import {StyleSheet} from 'react-native';

const loginStyles = StyleSheet.create({
  Container: {
    flex: 1,
    backgroundColor: Constants.Colors.backgrounGrey,
  },
  symtomsWrapper: {
    backgroundColor: Constants.Colors.primaryBlue,
    padding: 10,
    borderRadius: 10,
    marginRight: 10,
    marginBottom: 5,
  },
  shiftText: {
    color: Constants.Colors.primaryBlue,
    fontSize: 11,
    fontWeight: 'bold',
  },
  shiftWrapper: {
    // backgroundColor: Constants.Colors.primaryBlue,
    // height: 60,
    marginRight: '2%',
    marginVertical: '2%',
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: Constants.Colors.primaryBlue,
    width: '30%',
    marginVertical: 2,
    // alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  symptontextSytle: {
    color: 'white',
  },
  arrowIcon: {
    color: 'white',
    fontSize: 20,
  },
  consultBtnWrapper: {
    width: 180,
    marginTop: 20,
    height: 50,
    borderRadius: 10,
    backgroundColor: Constants.Colors.primaryGreen,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tagsContainer: {
    // backgroundColor: 'red',
    paddingHorizontal: 20,
    borderWidth: 1,
  },
  desContainer: {
    flex: 1,
    // alignItems: 'center',
  },
  profileBgWrapper: {
    height: 300,
    width: '100%',
    // backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalText: {
    marginBottom: 15,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    color: Constants.Colors.grey,
  },
  crossBtnWrapper: {
    width: 60,
    height: 60,
    // color: Constants.Colors.primaryGreen,
    // backgroundColor: 'red',
    // zIndex:9999,
    position: 'absolute',
    top: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  centeredView: {
    flex: 1,
    width: Constants.ScreenWidth,
    height: Constants.ScreenHeight,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 99999,
    backgroundColor: '#60606066',
  },
  modalView: {
    // margin: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECEEF5',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '80%',
    height: '60%',
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  backgroundImageStyle: {
    resizeMode: 'cover',
    width: '100%',
    height: 300,
    opacity: 0.3,
    position: 'absolute',
  },
  doctorAvatarStyle: {
    width: 140,
    height: 140,
    resizeMode: 'contain',
    borderRadius: 70,
  },
  profileHeadingStyle: {
    color: Constants.Colors.primaryBlue,
    fontSize: 18,
    fontWeight: 'bold',
    marginVertical: 5,
  },
  profileTitleStyle: {
    color: Constants.Colors.primaryBlue,
    fontSize: 18,
  },
  infoContainer: {
    width: '100%',
    backgroundColor: Constants.Colors.primaryBlue,
    height: 60,
    flexDirection: 'row',
  },
  infoWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoText: {
    color: 'white',
    fontSize: 17,
    fontWeight: 'bold',
  },
  textWrapper: {
    padding: 20,
    paddingVertical: 10,
    // backgroundColor: 'white',
  },
  textInfoStyle: {
    color: Constants.Colors.grey,
    fontSize: 15,
    textAlign: 'justify',
    marginTop: 10,
  },
  tagsWrapper: {
    // flexDirection: 'row',
    paddingHorizontal: 20,
    flex: 1,
    width: '100%',
    // alignItems: 'flex-start',
    // justifyContent: 'flex-start',
  },
  tagStyle: {},
  footerContainer: {
    // backgroundColor: Constants.Colors.primaryBgGrey,
    // height: 200,
    // borderWidth: 1,
    // padding: 20,
    // marginBottom: 30,
    paddingHorizontal: 20,
    width: '100%',
    flexDirection: 'row',
  },
  mapImage: {
    width: '100%',
    resizeMode: 'contain',
  },
  footerIconStyle: {
    fontSize: 35,
    color: Constants.Colors.primaryGreen,
  },
  crossTxtStyle: {
    fontSize: 30,
    color: Constants.Colors.primaryGreen,
    fontWeight: 'bold',
  },
  footerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    // backgroundColor: 'red',
    // justifyContent: 'center'
  },
  numberInputStyle: {
    width: 200,
    height: 45,
    paddingHorizontal: 20,
    color: Constants.Colors.grey,
    // textAlign: 'center',
    // borderWidth: 1,
    fontSize: 15,
    borderRadius: 25,
    backgroundColor: 'white',

    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  footerTxtStyle: {
    fontSize: 14,
    color: Constants.Colors.grey,
  },
});
export default loginStyles;
